AutoRun("ClipboardHelpAndSpell",CHS)
AutoRun("dm2",DM2)
;AutoRun("outlook","C:\\Program Files (x86)\\Microsoft Office\\Office14\\OUTLOOK.EXE")
;AutoRun("ToDoList",ToDoList)
AutoRun("Lingoes","C:\\Users\\wangweihua.CORP\\AppData\\Local\\Lingoes\\Translator\\lingoes-cn\\Lingoes.exe")
AutoRun("YouDaoDict","C:\\Program Files\\Youdao\\Dict\\YodaoDict.exe")