AutoRun("ClipboardHelpAndSpell",CHS)
AutoRun("dm2",DM2)
;AutoRun("outlook","C:\\Program Files (x86)\\Microsoft Office\\Office14\\OUTLOOK.EXE")
;AutoRun("ToDoList",ToDoList)
;AutoRun("Lingoes",Lingoes)
AutoRun("YouDaoDict",YodaoDict)
AutoRun("WeiChat", WeChat)
AutoRun("Fetion", Fetion)