;Auto-Generated Executable Paths
SublimeText := "D:\Program Files (x86)\Sublime Text 3\sublime_text.exe"
EditPlus := "C:\Program Files (x86)\EditPlus 3\editplus.exe"
PicPick := "C:\Program Files (x86)\PicPick\picpick.exe"
KMPlayer := "C:\Program Files\The KMPlayer\KMPlayer.exe"
CHS := "D:\Program Files\ClipboardHelpAndSpellPortable\ClipboardHelpAndSpell.exe"
QQ := "C:\Program Files (x86)\Tencent\QQ\Bin\QQ.exe"
Firefox := "D:\Program Files\Firefox26\App\Firefox\firefox.exe"
BeyondCompare := "D:\Program Files\bcompare\BCompare.exe"
FileZilla := "C:\Program Files (x86)\FileZilla FTP Client\filezilla.exe"
YoudaoNote := "C:\Program Files (x86)\Youdao\YoudaoNote\RunYNote.exe"
XShell := "C:\Program Files (x86)\NetSarang\Xshell 4\Xshell.exe"
Thunder := "C:\Program Files (x86)\Thunder Network\Thunder\Program\Thunder.exe"
Lingoes := "C:\Users\wangweihua.CORP\AppData\Local\Lingoes\Translator\lingoes-cn\Lingoes.exe"
Outlook := "C:\Program Files (x86)\Microsoft Office\Office14\OUTLOOK.EXE"
ToDoList := "D:\Program Files\ToDoList\ToDoList.exe"
Everything := "C:\Program Files (x86)\Everything\Everything.exe"
Chrome := "C:\Users\wangweihua.CORP\AppData\Local\Google\Chrome\Application\chrome.exe"
